e2e/regression: subtest for waiting
This gives easier error indication in the test output:

    --- FAIL: TestRegression/job (367.30s)
        --- PASS: TestRegression/job/generate (4.32s)
        --- PASS: TestRegression/job/apply (0.20s)
        --- PASS: TestRegression/job/set (0.72s)
        --- PASS: TestRegression/job/verify (1.60s)
        --- FAIL: TestRegression/job/wait-for-resources (360.35s)